# Generated by Django 3.0.5 on 2020-05-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_auto_20200518_1512'),
        ('bookings', '0002_auto_20200518_1547'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('classID', 'phone_number')},
        ),
    ]
