# Generated by Django 3.0.5 on 2020-05-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_auto_20200518_1512'),
        ('bookings', '0003_auto_20200518_1600'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('classID', 'email')},
        ),
    ]
