# Generated by Django 3.0.5 on 2020-05-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20200519_0820'),
        ('bookings', '0003_merge_20200519_1313'),
    ]

    operations = [
    ]
