# Generated by Django 3.0.5 on 2020-05-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0003_auto_20200428_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('image', models.ImageField(default='media/media/pictures/default_instructor.jpg', upload_to='media/media/pictures')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
                ('instructorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.Instructor')),
            ],
            options={
                'unique_together': {('instructorID', 'activityID')},
            },
        ),
    ]
