# Generated by Django 3.0.5 on 2020-05-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(default='pictures/default_instructor.jpg', upload_to='pictures'),
        ),
    ]
