# Generated by Django 3.0.5 on 2020-05-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='pictures/default_instructor.jpg', upload_to='pictures'),
        ),
    ]
