# Generated by Django 3.0.5 on 2020-05-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('street_address', models.CharField(max_length=120)),
                ('postal_code', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=120)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
    ]
