# Generated by Django 3.0.5 on 2020-04-28 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200428_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='class',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
    ]
