# Generated by Django 3.0.5 on 2020-04-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20200428_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
