# Generated by Django 3.0.5 on 2020-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20200507_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='location',
            field=models.CharField(max_length=120),
        ),
    ]
