# Generated by Django 3.0.5 on 2020-05-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_auto_20200518_1512'),
        ('classes', '0011_auto_20200519_1044'),
    ]

    operations = [
    ]
