# Generated by Django 3.0.5 on 2020-05-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_merge_20200519_1313'),
        ('classes', '0012_merge_20200519_0823'),
    ]

    operations = [
    ]
